project_name: freeport

builds:
  - env:
      - CGO_ENABLED=0
    binary: freeport
    goos:
      - linux
      - darwin
    goarch:
      - "386"
      - amd64
      - arm64
    goarm:
      - "6"
    main: ./cmd/freeport
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

source:
  format: tar.gz
  name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  files:
  - licence*
  - LICENCE*
  - license*
  - LICENSE*
  - readme*
  - README*
  - changelog*
  - CHANGELOG*

snapshot:
  name_template: SNAPSHOT-{{ .Commit }}

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'

# Create RPM and .DEB files
nfpms:
  - vendor: Tri Le Minh
    maintainer: Tri Le Minh <ansidev@gmail.com>
    description: Get a free open TCP port that is ready to use.
    license: BSD
    formats:
      - deb
      - rpm

# Homebrew repos
brews:
  - tap:
      owner: ansidev
      name: homebrew-repo
      branch: main

    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com

    description: "Get a free open TCP port that is ready to use."
